pipeline {
    agent any 
    stages{
        stage('Install'){
            steps{
                bat 'npm ci'
            }
        }   
            stage('Test'){
                steps {
                    bat 'npm test'
                }
            }
            stage('Build'){
                steps {
                    bat 'npm run build'
                }
            }
            stage('Docker build'){
                steps{
                    bat "docker build -t gopimano1997/web:${env.BUILD_NUMBER} ."
                }
            }
        }
        post{
            success{archiveArtifacts 'build/**'}
            cleanup{cleanWs()}
        }
    }