pipeline {
    agent any 
    environment{
        TAG = "${env.BUILD_NUMBER}"
    }
    stages{
        stage('Install'){
            steps{
                bat 'npm ci'
            }
        }   
            stage('Test'){
                steps {
                    bat 'npm test'
                }
            }
            stage('Build'){
                steps {
                    bat 'npm run build'
                }
            }
            stage('Docker build'){
                steps{
                    bat "docker build -t gopimano1997/web:${env.BUILD_NUMBER} ."
                }
            }
            stage('Docker push'){
                steps{
                    withCredentials([usernamePassword(credentialsId: 'dockerhub' , usernameVariable: 'USER', passwordVariable: 'PASS')]){
                    bat 'echo %PASS%| docker login -u %USER% --password-stdin'
                    bat "docker push gopimano1997/web:${env.BUILD_NUMBER}"
                    }
                }
            }
            stage('Deploy'){
                steps{
                    bat 'docker compose up -d'
                }
            }
            stage('Smoke Test'){
                steps{
                    sleep 5
                    bat 'curl -f http://localhost:8085'
                }
            }
        }
        post{
            success{archiveArtifacts 'build/**'}
            cleanup{cleanWs()}
        }
    }